services:
  App\Controller\PrinterController:
    class: App\Controller\PrinterController
    autowire: true
    public: true
  App\Controller\PlasticController:
    class: App\Controller\PlasticController
    autowire: true
    public: true