controllers:
    resource: ../src/Controller/
    type: attribute

getPrinter:
    path: /getPrinter
    controller: App\Controller\PrinterController::getPrinter

createPrinter:
    path: /createPrinter
    controller: App\Controller\PrinterController::createPrinter

getPlastic:
    path: /getPlastic
    controller: App\Controller\PlasticController::getPlastic

createPlastic:
    path: /createPlastic
    controller: App\Controller\PlasticController::createPlastic